const languages = {
  "Español": {
    "posts": "Publicaciones",
    "top": "Top de la semana",
    "config": "Configuración",
    "notifications": "Notificaciones",
    "sec": "Seguridad",
    "priv": "Privacidad",
    "langs": "Idiomas",
    "logout": "Cerrar Sesión",
    "community creation": "¿Te interesa crear una Aldea?",
    "create": "¡Crear!",
    "followers": "Seguidores",
    "winners": "¡Ganadores!",
    "public posts": "Posts públicos",
    "marketplace": "Tienda",
    "desc": "Descripción",
    "community rules": "Normas comunidad",
    "save": "Guardar",
    "admission1": "Tienes ",
    "admission2": "peticiones",
    "admission3": "de admisión pendientes",
    "congrats": "Enhorabuena a los ganadores!",
    "qs type": "Tipo de Venta Rápida: ",
    "list": "Lista",
    "random": "Aleatorio",
    "game": "Juego",
    "model": "Modelo",
    "oops": "Ups...",
    "quickstrikes empty":
        "Parece que en estos momentos no hay ningún quickstrike activo.",
    "chats empty": "Parece que en estos momentos no tienes ningun chat activo.",
  },
  "English": {
    "posts": "Posts",
    "top": "Weekly Top",
    "config": "Settings",
    "notifications": "Notifications",
    "sec": "Security",
    "priv": "Privacy",
    "langs": "Languages",
    "logout": "Log out",
    "community creation": "Want to create an Aldea?",
    "create": "Create!",
    "followers": "Followers",
    "winners": "Winners!",
    "public posts": "Public posts",
    "marketplace": "Marketplace",
    "desc": "Description",
    "community rules": "Community rules",
    "save": "Save",
    "admission1": "There are",
    "admission2": "admission requests",
    "admission3": "pending",
    "congrats": "Congratulations to the winners!",
    "qs type": "QuickStrike Type: ",
    "list": "List",
    "random": "Random",
    "game": "Game",
    "model": "Model",
    "oops": "Oops...",
    "quickstrikes empty":
        "Seems like there are no active quickstrikes at the moment.",
    "chats empty": "Seems like you don't have any active chats at the moment."
  }
};
