const String LoginViewRoute = "LoginView";
const String SignUpViewRoute = "SignUp";
const String ConfirmPhoneNumberRoute = "ConfirmPhoneNumber";
const String HomeViewRoute = "HomeView";
const String CommunityViewRoute = "CommunityView";
const String RequestsViewRoute = "RequestsView";
const String VouchViewRoute = "VouchView";
const String ChatViewRoute = "ChatView";
const String OtherProfileViewRoute = "OtherProfileView";
const String ProfileSettingsViewRoute = "ProfileSettingsView";
const String CommunityCreationViewRoute = "CommunityCreationView";
const String AdminScreenViewRoute = 'AdminScreenView';
const String DetailedCommunityCreationViewRoute =
    'DetailedCommunityCreationView';
const String CommunitySettingsViewRoute = 'CommunitySettingsView';
const String CommentsViewRoute = 'CommentsView';
const String CommunitiesProfileViewRoute = 'CommunitiesProfileView';
const String HeroScreenRoute = 'HeroScreen';
const String CommunityUsersAdminRoute= 'CommunityUsersAdminView';
